
from src.gen_files import file_utils as fu, paths as p


testng_server_content = """testngfile,server
testng.xml,-
testngAPIData.xml,-
testngAcqAng.xml,-
testngAcqConfig.xml,-
testngAcqConfigNG.xml,-
testngAcqManageSetNG.xml,-
testngAcqNG_Part1.xml,-
testngAcqNG_Part2.xml,-
testngAcqNG_Part3.xml,-
testngAcqNG_Part4.xml,-
testngAcqNG_Part5.xml,-
testngAcqNG_Part6.xml,-
testngAcqNG_Part7.xml,-
testngAcqNetwork.xml,-
testngAcqNetworkNG.xml,-
testngAcqProblematic.xml,-
testngAcq_Part1.xml,-
testngAcq_Part2.xml,-
testngAcq_Part3.xml,-
testngAcq_Part4.xml,-
testngAcq_Part5.xml,-
testngAcq_Part6.xml,-
testngAcq_weekend.xml,-
testngAfterClone_Primo_CrossServers.xml,-
testngAfterClone_QAC01.xml,QAC01
testngAfterClone_QAC01_Base.xml,QAC01
testngAfterClone_QAC01_Digital.xml,QAC01
testngAfterClone_QAC01_Fulf.xml,QAC01
testngAfterClone_QAC01_Letters.xml,QAC01
testngAfterClone_QAC01_MailConf.xml,QAC01
testngAfterClone_QAC01_Primo.xml,QAC01
testngAfterClone_QAC01_Rsh.xml,QAC01
testngAfterClone_QAC01_Users.xml,QAC01
testngAfterClone_SQA_EU01.xml,SQA_EU01
testngAfterClone_SQA_EU02.xml,-
testngAfterClone_SQA_EU04.xml,-
testngAfterClone_SQA_NA01.xml,SQA_NA01
testngAlliance.xml,-
testngAlmaEConfig.xml,-
testngAlmaENetworkConfig.xml,-
testngAlmaE_Part1.xml,-
testngAlmaE_Part2.xml,-
testngAnalysisOfTestResults.xml,-
testngAnalytics.xml,-
testngAnalyticsNewUi.xml,-
testngApiJson.xml,-
testngAuthoritiesDataProjectSingleTest.xml,-
testngAuthorityDataProject.xml,-
testngAuthority_Part1.xml,-
testngAuthority_Part2.xml,-
testngAuthority_Part3.xml,-
testngAuthority_Part4.xml,-
testngAvishai.xml,IGNORE
testngBibSys.xml,-
testngCDI.xml,-
testngCleanupGMail.xml,-
testngCounter.xml,-
testngDBQAQueries.xml,-
testngDBQASingleQuery.xml,-
testngDBvisualizer.xml,-
testngDana.xml,IGNORE
testngDeveloperPortal.xml,-
testngDigital1.xml,-
testngDigital2.xml,-
testngDigital3.xml,-
testngDigital4.xml,-
testngDigital5.xml,-
testngDigitalManageSetsNG.xml,-
testngDownloadResultsFromJenkins.xml,-
testngEBookCentralJob.xml,-
testngEBookCentralJobRes.xml,-
testngERM1.xml,QAC01
testngERM2.xml,QAC01
testngEli.xml,IGNORE
testngElisheva.xml,IGNORE
testngExportPortfolioUrl.xml,-
testngFeatureFlagsRestoration.xml,-
testngFixLogin.xml,-
testngFulf1.xml,-
testngFulf2.xml,-
testngFulf3.xml,-
testngFulf4.xml,-
testngFulf5.xml,-
testngFulf6.xml,-
testngFulfConfig.xml,-
testngFulfConsortia.xml,-
testngFulfNG1.xml,-
testngFulfNG2.xml,-
testngFulfNG3.xml,-
testngFulfNG4.xml,-
testngFulfNG5.xml,-
testngFulfNG6.xml,-
testngFulfNetworkCZ.xml,-
testngFulfRFID.xml,-
testngFulfRshNetwork.xml,-
testngGuy.xml,IGNORE
testngHackathon.xml,-
testngHadarK.xml,IGNORE
testngHaim.xml,IGNORE
testngIdo.xml,IGNORE
testngIndexingJob.xml,-
testngLeganto.xml,-
testngLegantoDevelopers.xml,-
testngMDE_QAC01_SQA03_Part1.xml,QAC01
testngMDE_QAC01_SQA03_Part2.xml,QAC01
testngMDE_SQA_EU04.xml,-
testngMayM.xml,-
testngMigration_CheckResults.xml,-
testngMigration_DbTablesAndColumns.xml,-
testngMigration_RunLoaders.xml,-
testngMobile.xml,-
testngNgrs_Multi_ENV.xml,-
testngNgrs_QAC01.xml,QAC01
testngNgrs_SQANA02.xml,-
testngNgrs_SQA_EU01.xml,SQA_EU01
testngNgrs_SQA_EU01_2.xml,SQA_EU01
testngOBI.xml,-
testngOBI_QQ.xml,-
testngOBI_QQ_Base.xml,-
testngPRM_Part1_SQA03_NA03.xml,QAC01
testngPRM_Part2_SQA03_NA03.xml,QAC01
testngPRM_Part3_SQA03_NA03.xml,QAC01
testngPRM_Part4_SQA03_NA03.xml,QAC01
testngPostDeploymentAcq.xml,-
testngPostDeploymentFulf.xml,-
testngPostDeploymentRM.xml,-
testngPrimo.xml,-
testngPrimoNetwork.xml,-
testngPrimoWeekends.xml,-
testngProviderZone.xml,-
testngPublishingNetwork.xml,-
testngPublishingSplit1.xml,-
testngPublishingSplit2.xml,-
testngPublishingSplit3.xml,-
testngPublishingSplit_sqa_eu01_1.xml,SQA_EU01
testngPublishingSplit_sqa_eu01_2.xml,SQA_EU01
testngPublishingSplit_sqa_eu01_3.xml,SQA_EU01
testngPublishingSplit_sqa_na01_1.xml,SQA_NA01
testngPublishingSplit_sqa_na01_2.xml,SQA_NA01
testngPublishingWeekends.xml,-
testngPublishing_QAC01.xml,QAC01
testngRMConfigAfterClone.xml,-
testngRM_EX_SQA03_NA03.xml,QAC01
testngRSh.xml,-
testngRSh1.xml,-
testngRSh1NG.xml,-
testngRSh1NGPart2.xml,-
testngRSh1Part2.xml,-
testngRSh2.xml,-
testngRSh2NGPart2.xml,-
testngRSh2Part2.xml,-
testngRSh3.xml,-
testngRShNetwork.xml,-
testngRShNetworkNG.xml,-
testngRShNetworkNGPart2.xml,-
testngRShNetworkPart2.xml,-
testngRSh_QAC01-NEU.xml,QAC01
testngRSh_QAC01-VCU.xml,QAC01
testngRSh_RAPIDILL_QAC01.xml,QAC01
testngRanR.xml,-
testngRapidoGTI_QAC01.xml,QAC01
testngRapidoGTI_SQA03_NA03.xml,QAC01
testngRapidoGTI_SQA_EU04.xml,-
testngRapidoSA_URM05.xml,-
testngRapido_AfterClone.xml,-
testngRapido_Config_MultiENV_AfterClone.xml,-
testngRapido_Multi_ENV.xml,-
testngRapido_SQA03_NA03.xml,QAC01
testngRapido_SQA_EU01_1.xml,SQA_EU01
testngRapido_SQA_EU01_2.xml,SQA_EU01
testngRapido_SQA_EU02_MultiplePod.xml,-
testngRapido_SQA_EU03_1.xml,-
testngRapido_SQA_NA01_1.xml,SQA_NA01
testngRapido_SQA_NA01_2.xml,SQA_NA01
testngRapido_SQA_NA01_3.xml,SQA_NA01
testngRialto1.xml,-
testngRialto2.xml,-
testngRialto3.xml,-
testngRialto4.xml,-
testngRialto5.xml,-
testngRialto6.xml,-
testngSendRequestsNotificationCheckResults_1.xml,-
testngSendRequestsNotification_1.xml,-
testngShayli.xml,IGNORE
testngSmartRecommendations.xml,-
testngSmartRecommendationsNet.xml,-
testngSmoke.xml,-
testngSyncCZJob.xml,-
testngSyncCZ_All.xml,-
testngSyncTestrailIds.xml,-
testngUResolverLinks.xml,-
testngUsers1.xml,-
testngUsers2.xml,-
testngUsersNetwork.xml,-
testngUsersWeekends.xml,-
testngUsers_FULFNG.xml,-
testngZ3950.xml,-
testngZalman.xml,IGNORE
testng_ACC.xml,-
testng_ConfigAfterClone_AlmaE.xml,-
testng_ConfigAfterClone_AlmaENetwork.xml,-
testng_GTI.xml,-
testng_Jenkins_Uptime.xml,-
testng_Release_MDE_SQA03_EU01.xml,-
testng_Release_MDE_SQA_NA01.xml,SQA_NA01
testng_SQA_EU01_Authority_Part1.xml,SQA_EU01
testng_SQA_EU01_Authority_Part2.xml,SQA_EU01
testng_SQA_EU01_ERM.xml,SQA_EU01
testng_SQA_EU01_MDE.xml,SQA_EU01
testng_SQA_NA01_ERM.xml,SQA_NA01
testng_SQA_NA01_MDE.xml,SQA_NA01
testng_SQA_NA01_PRM.xml,SQA_NA01
testngYaelS.xml,IGNORE
"""


def create_testng_server_csv():
    fu.write_txt_to_file(p.testng_server_csv_path, testng_server_content)